
configuration: Debug

branches:
  only:
    - master

before_build: 
  - nuget restore PInvoke.sln

build:
  project: PInvoke.sln
  verbosity: minimal

test:
  assemblies:
     - PInvoke.Test\bin\Debug\PInvoke.Test.dll     
